/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VocabularyRouteImport } from './routes/vocabulary'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as QuestRouteImport } from './routes/quest'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as GrammarRouteImport } from './routes/grammar'
import { Route as GamesRouteImport } from './routes/games'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DailyRouteImport } from './routes/daily'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesIndexRouteImport } from './routes/games.index'
import { Route as StoriesIdRouteImport } from './routes/stories.$id'
import { Route as GuideDifficultyRouteImport } from './routes/guide.difficulty'
import { Route as GrammarVerbsRouteImport } from './routes/grammar.verbs'
import { Route as GrammarConnectionsRouteImport } from './routes/grammar.connections'
import { Route as GrammarConjugationRouteImport } from './routes/grammar.conjugation'
import { Route as GrammarAspectRouteImport } from './routes/grammar.aspect'
import { Route as GamesWordchainRouteImport } from './routes/games.wordchain'
import { Route as GamesSentenceRouteImport } from './routes/games.sentence'
import { Route as GamesQuizRouteImport } from './routes/games.quiz'
import { Route as GamesMemoryRouteImport } from './routes/games.memory'
import { Route as GamesMatchRouteImport } from './routes/games.match'
import { Route as GamesListeningRouteImport } from './routes/games.listening'
import { Route as GamesFillblankRouteImport } from './routes/games.fillblank'
import { Route as GamesCrosswordRouteImport } from './routes/games.crossword'
import { Route as GamesConjugationRouteImport } from './routes/games.conjugation'
import { Route as GamesBattleRouteImport } from './routes/games.battle'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as GrammarCasesCaseRouteImport } from './routes/grammar.cases.$case'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const VocabularyRoute = VocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestRoute = QuestRouteImport.update({
  id: '/quest',
  path: '/quest',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const GrammarRoute = GrammarRouteImport.update({
  id: '/grammar',
  path: '/grammar',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyRoute = DailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GamesRoute,
} as any)
const StoriesIdRoute = StoriesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StoriesRoute,
} as any)
const GuideDifficultyRoute = GuideDifficultyRouteImport.update({
  id: '/guide/difficulty',
  path: '/guide/difficulty',
  getParentRoute: () => rootRouteImport,
} as any)
const GrammarVerbsRoute = GrammarVerbsRouteImport.update({
  id: '/verbs',
  path: '/verbs',
  getParentRoute: () => GrammarRoute,
} as any)
const GrammarConnectionsRoute = GrammarConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => GrammarRoute,
} as any)
const GrammarConjugationRoute = GrammarConjugationRouteImport.update({
  id: '/conjugation',
  path: '/conjugation',
  getParentRoute: () => GrammarRoute,
} as any)
const GrammarAspectRoute = GrammarAspectRouteImport.update({
  id: '/aspect',
  path: '/aspect',
  getParentRoute: () => GrammarRoute,
} as any)
const GamesWordchainRoute = GamesWordchainRouteImport.update({
  id: '/wordchain',
  path: '/wordchain',
  getParentRoute: () => GamesRoute,
} as any)
const GamesSentenceRoute = GamesSentenceRouteImport.update({
  id: '/sentence',
  path: '/sentence',
  getParentRoute: () => GamesRoute,
} as any)
const GamesQuizRoute = GamesQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => GamesRoute,
} as any)
const GamesMemoryRoute = GamesMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => GamesRoute,
} as any)
const GamesMatchRoute = GamesMatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => GamesRoute,
} as any)
const GamesListeningRoute = GamesListeningRouteImport.update({
  id: '/listening',
  path: '/listening',
  getParentRoute: () => GamesRoute,
} as any)
const GamesFillblankRoute = GamesFillblankRouteImport.update({
  id: '/fillblank',
  path: '/fillblank',
  getParentRoute: () => GamesRoute,
} as any)
const GamesCrosswordRoute = GamesCrosswordRouteImport.update({
  id: '/crossword',
  path: '/crossword',
  getParentRoute: () => GamesRoute,
} as any)
const GamesConjugationRoute = GamesConjugationRouteImport.update({
  id: '/conjugation',
  path: '/conjugation',
  getParentRoute: () => GamesRoute,
} as any)
const GamesBattleRoute = GamesBattleRouteImport.update({
  id: '/battle',
  path: '/battle',
  getParentRoute: () => GamesRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const GrammarCasesCaseRoute = GrammarCasesCaseRouteImport.update({
  id: '/cases/$case',
  path: '/cases/$case',
  getParentRoute: () => GrammarRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/daily': typeof DailyRoute
  '/dashboard': typeof DashboardRoute
  '/games': typeof GamesRouteWithChildren
  '/grammar': typeof GrammarRouteWithChildren
  '/mcp': typeof McpRoute
  '/quest': typeof QuestRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stories': typeof StoriesRouteWithChildren
  '/vocabulary': typeof VocabularyRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/games/battle': typeof GamesBattleRoute
  '/games/conjugation': typeof GamesConjugationRoute
  '/games/crossword': typeof GamesCrosswordRoute
  '/games/fillblank': typeof GamesFillblankRoute
  '/games/listening': typeof GamesListeningRoute
  '/games/match': typeof GamesMatchRoute
  '/games/memory': typeof GamesMemoryRoute
  '/games/quiz': typeof GamesQuizRoute
  '/games/sentence': typeof GamesSentenceRoute
  '/games/wordchain': typeof GamesWordchainRoute
  '/grammar/aspect': typeof GrammarAspectRoute
  '/grammar/conjugation': typeof GrammarConjugationRoute
  '/grammar/connections': typeof GrammarConnectionsRoute
  '/grammar/verbs': typeof GrammarVerbsRoute
  '/guide/difficulty': typeof GuideDifficultyRoute
  '/stories/$id': typeof StoriesIdRoute
  '/games/': typeof GamesIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/grammar/cases/$case': typeof GrammarCasesCaseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/daily': typeof DailyRoute
  '/dashboard': typeof DashboardRoute
  '/grammar': typeof GrammarRouteWithChildren
  '/mcp': typeof McpRoute
  '/quest': typeof QuestRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stories': typeof StoriesRouteWithChildren
  '/vocabulary': typeof VocabularyRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/games/battle': typeof GamesBattleRoute
  '/games/conjugation': typeof GamesConjugationRoute
  '/games/crossword': typeof GamesCrosswordRoute
  '/games/fillblank': typeof GamesFillblankRoute
  '/games/listening': typeof GamesListeningRoute
  '/games/match': typeof GamesMatchRoute
  '/games/memory': typeof GamesMemoryRoute
  '/games/quiz': typeof GamesQuizRoute
  '/games/sentence': typeof GamesSentenceRoute
  '/games/wordchain': typeof GamesWordchainRoute
  '/grammar/aspect': typeof GrammarAspectRoute
  '/grammar/conjugation': typeof GrammarConjugationRoute
  '/grammar/connections': typeof GrammarConnectionsRoute
  '/grammar/verbs': typeof GrammarVerbsRoute
  '/guide/difficulty': typeof GuideDifficultyRoute
  '/stories/$id': typeof StoriesIdRoute
  '/games': typeof GamesIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/grammar/cases/$case': typeof GrammarCasesCaseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/daily': typeof DailyRoute
  '/dashboard': typeof DashboardRoute
  '/games': typeof GamesRouteWithChildren
  '/grammar': typeof GrammarRouteWithChildren
  '/mcp': typeof McpRoute
  '/quest': typeof QuestRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stories': typeof StoriesRouteWithChildren
  '/vocabulary': typeof VocabularyRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/games/battle': typeof GamesBattleRoute
  '/games/conjugation': typeof GamesConjugationRoute
  '/games/crossword': typeof GamesCrosswordRoute
  '/games/fillblank': typeof GamesFillblankRoute
  '/games/listening': typeof GamesListeningRoute
  '/games/match': typeof GamesMatchRoute
  '/games/memory': typeof GamesMemoryRoute
  '/games/quiz': typeof GamesQuizRoute
  '/games/sentence': typeof GamesSentenceRoute
  '/games/wordchain': typeof GamesWordchainRoute
  '/grammar/aspect': typeof GrammarAspectRoute
  '/grammar/conjugation': typeof GrammarConjugationRoute
  '/grammar/connections': typeof GrammarConnectionsRoute
  '/grammar/verbs': typeof GrammarVerbsRoute
  '/guide/difficulty': typeof GuideDifficultyRoute
  '/stories/$id': typeof StoriesIdRoute
  '/games/': typeof GamesIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/grammar/cases/$case': typeof GrammarCasesCaseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/daily'
    | '/dashboard'
    | '/games'
    | '/grammar'
    | '/mcp'
    | '/quest'
    | '/sitemap.xml'
    | '/stories'
    | '/vocabulary'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/games/battle'
    | '/games/conjugation'
    | '/games/crossword'
    | '/games/fillblank'
    | '/games/listening'
    | '/games/match'
    | '/games/memory'
    | '/games/quiz'
    | '/games/sentence'
    | '/games/wordchain'
    | '/grammar/aspect'
    | '/grammar/conjugation'
    | '/grammar/connections'
    | '/grammar/verbs'
    | '/guide/difficulty'
    | '/stories/$id'
    | '/games/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/grammar/cases/$case'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/daily'
    | '/dashboard'
    | '/grammar'
    | '/mcp'
    | '/quest'
    | '/sitemap.xml'
    | '/stories'
    | '/vocabulary'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/games/battle'
    | '/games/conjugation'
    | '/games/crossword'
    | '/games/fillblank'
    | '/games/listening'
    | '/games/match'
    | '/games/memory'
    | '/games/quiz'
    | '/games/sentence'
    | '/games/wordchain'
    | '/grammar/aspect'
    | '/grammar/conjugation'
    | '/grammar/connections'
    | '/grammar/verbs'
    | '/guide/difficulty'
    | '/stories/$id'
    | '/games'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/grammar/cases/$case'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/daily'
    | '/dashboard'
    | '/games'
    | '/grammar'
    | '/mcp'
    | '/quest'
    | '/sitemap.xml'
    | '/stories'
    | '/vocabulary'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/games/battle'
    | '/games/conjugation'
    | '/games/crossword'
    | '/games/fillblank'
    | '/games/listening'
    | '/games/match'
    | '/games/memory'
    | '/games/quiz'
    | '/games/sentence'
    | '/games/wordchain'
    | '/grammar/aspect'
    | '/grammar/conjugation'
    | '/grammar/connections'
    | '/grammar/verbs'
    | '/guide/difficulty'
    | '/stories/$id'
    | '/games/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/grammar/cases/$case'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DailyRoute: typeof DailyRoute
  DashboardRoute: typeof DashboardRoute
  GamesRoute: typeof GamesRouteWithChildren
  GrammarRoute: typeof GrammarRouteWithChildren
  McpRoute: typeof McpRoute
  QuestRoute: typeof QuestRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StoriesRoute: typeof StoriesRouteWithChildren
  VocabularyRoute: typeof VocabularyRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  GuideDifficultyRoute: typeof GuideDifficultyRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vocabulary': {
      id: '/vocabulary'
      path: '/vocabulary'
      fullPath: '/vocabulary'
      preLoaderRoute: typeof VocabularyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quest': {
      id: '/quest'
      path: '/quest'
      fullPath: '/quest'
      preLoaderRoute: typeof QuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grammar': {
      id: '/grammar'
      path: '/grammar'
      fullPath: '/grammar'
      preLoaderRoute: typeof GrammarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily': {
      id: '/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof DailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof GamesRoute
    }
    '/stories/$id': {
      id: '/stories/$id'
      path: '/$id'
      fullPath: '/stories/$id'
      preLoaderRoute: typeof StoriesIdRouteImport
      parentRoute: typeof StoriesRoute
    }
    '/guide/difficulty': {
      id: '/guide/difficulty'
      path: '/guide/difficulty'
      fullPath: '/guide/difficulty'
      preLoaderRoute: typeof GuideDifficultyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grammar/verbs': {
      id: '/grammar/verbs'
      path: '/verbs'
      fullPath: '/grammar/verbs'
      preLoaderRoute: typeof GrammarVerbsRouteImport
      parentRoute: typeof GrammarRoute
    }
    '/grammar/connections': {
      id: '/grammar/connections'
      path: '/connections'
      fullPath: '/grammar/connections'
      preLoaderRoute: typeof GrammarConnectionsRouteImport
      parentRoute: typeof GrammarRoute
    }
    '/grammar/conjugation': {
      id: '/grammar/conjugation'
      path: '/conjugation'
      fullPath: '/grammar/conjugation'
      preLoaderRoute: typeof GrammarConjugationRouteImport
      parentRoute: typeof GrammarRoute
    }
    '/grammar/aspect': {
      id: '/grammar/aspect'
      path: '/aspect'
      fullPath: '/grammar/aspect'
      preLoaderRoute: typeof GrammarAspectRouteImport
      parentRoute: typeof GrammarRoute
    }
    '/games/wordchain': {
      id: '/games/wordchain'
      path: '/wordchain'
      fullPath: '/games/wordchain'
      preLoaderRoute: typeof GamesWordchainRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/sentence': {
      id: '/games/sentence'
      path: '/sentence'
      fullPath: '/games/sentence'
      preLoaderRoute: typeof GamesSentenceRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/quiz': {
      id: '/games/quiz'
      path: '/quiz'
      fullPath: '/games/quiz'
      preLoaderRoute: typeof GamesQuizRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/memory': {
      id: '/games/memory'
      path: '/memory'
      fullPath: '/games/memory'
      preLoaderRoute: typeof GamesMemoryRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/match': {
      id: '/games/match'
      path: '/match'
      fullPath: '/games/match'
      preLoaderRoute: typeof GamesMatchRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/listening': {
      id: '/games/listening'
      path: '/listening'
      fullPath: '/games/listening'
      preLoaderRoute: typeof GamesListeningRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/fillblank': {
      id: '/games/fillblank'
      path: '/fillblank'
      fullPath: '/games/fillblank'
      preLoaderRoute: typeof GamesFillblankRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/crossword': {
      id: '/games/crossword'
      path: '/crossword'
      fullPath: '/games/crossword'
      preLoaderRoute: typeof GamesCrosswordRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/conjugation': {
      id: '/games/conjugation'
      path: '/conjugation'
      fullPath: '/games/conjugation'
      preLoaderRoute: typeof GamesConjugationRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/battle': {
      id: '/games/battle'
      path: '/battle'
      fullPath: '/games/battle'
      preLoaderRoute: typeof GamesBattleRouteImport
      parentRoute: typeof GamesRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grammar/cases/$case': {
      id: '/grammar/cases/$case'
      path: '/cases/$case'
      fullPath: '/grammar/cases/$case'
      preLoaderRoute: typeof GrammarCasesCaseRouteImport
      parentRoute: typeof GrammarRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface GamesRouteChildren {
  GamesBattleRoute: typeof GamesBattleRoute
  GamesConjugationRoute: typeof GamesConjugationRoute
  GamesCrosswordRoute: typeof GamesCrosswordRoute
  GamesFillblankRoute: typeof GamesFillblankRoute
  GamesListeningRoute: typeof GamesListeningRoute
  GamesMatchRoute: typeof GamesMatchRoute
  GamesMemoryRoute: typeof GamesMemoryRoute
  GamesQuizRoute: typeof GamesQuizRoute
  GamesSentenceRoute: typeof GamesSentenceRoute
  GamesWordchainRoute: typeof GamesWordchainRoute
  GamesIndexRoute: typeof GamesIndexRoute
}

const GamesRouteChildren: GamesRouteChildren = {
  GamesBattleRoute: GamesBattleRoute,
  GamesConjugationRoute: GamesConjugationRoute,
  GamesCrosswordRoute: GamesCrosswordRoute,
  GamesFillblankRoute: GamesFillblankRoute,
  GamesListeningRoute: GamesListeningRoute,
  GamesMatchRoute: GamesMatchRoute,
  GamesMemoryRoute: GamesMemoryRoute,
  GamesQuizRoute: GamesQuizRoute,
  GamesSentenceRoute: GamesSentenceRoute,
  GamesWordchainRoute: GamesWordchainRoute,
  GamesIndexRoute: GamesIndexRoute,
}

const GamesRouteWithChildren = GamesRoute._addFileChildren(GamesRouteChildren)

interface GrammarRouteChildren {
  GrammarAspectRoute: typeof GrammarAspectRoute
  GrammarConjugationRoute: typeof GrammarConjugationRoute
  GrammarConnectionsRoute: typeof GrammarConnectionsRoute
  GrammarVerbsRoute: typeof GrammarVerbsRoute
  GrammarCasesCaseRoute: typeof GrammarCasesCaseRoute
}

const GrammarRouteChildren: GrammarRouteChildren = {
  GrammarAspectRoute: GrammarAspectRoute,
  GrammarConjugationRoute: GrammarConjugationRoute,
  GrammarConnectionsRoute: GrammarConnectionsRoute,
  GrammarVerbsRoute: GrammarVerbsRoute,
  GrammarCasesCaseRoute: GrammarCasesCaseRoute,
}

const GrammarRouteWithChildren =
  GrammarRoute._addFileChildren(GrammarRouteChildren)

interface StoriesRouteChildren {
  StoriesIdRoute: typeof StoriesIdRoute
}

const StoriesRouteChildren: StoriesRouteChildren = {
  StoriesIdRoute: StoriesIdRoute,
}

const StoriesRouteWithChildren =
  StoriesRoute._addFileChildren(StoriesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DailyRoute: DailyRoute,
  DashboardRoute: DashboardRoute,
  GamesRoute: GamesRouteWithChildren,
  GrammarRoute: GrammarRouteWithChildren,
  McpRoute: McpRoute,
  QuestRoute: QuestRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StoriesRoute: StoriesRouteWithChildren,
  VocabularyRoute: VocabularyRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  GuideDifficultyRoute: GuideDifficultyRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
