/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VocabularyRouteImport } from './routes/vocabulary'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as GrammarRouteImport } from './routes/grammar'
import { Route as GamesRouteImport } from './routes/games'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DailyRouteImport } from './routes/daily'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoriesIdRouteImport } from './routes/stories.$id'
import { Route as GrammarVerbsRouteImport } from './routes/grammar.verbs'
import { Route as GrammarConnectionsRouteImport } from './routes/grammar.connections'
import { Route as GrammarConjugationRouteImport } from './routes/grammar.conjugation'
import { Route as GrammarAspectRouteImport } from './routes/grammar.aspect'
import { Route as GamesWordchainRouteImport } from './routes/games.wordchain'
import { Route as GamesSentenceRouteImport } from './routes/games.sentence'
import { Route as GamesQuizRouteImport } from './routes/games.quiz'
import { Route as GamesMemoryRouteImport } from './routes/games.memory'
import { Route as GamesMatchRouteImport } from './routes/games.match'
import { Route as GamesListeningRouteImport } from './routes/games.listening'
import { Route as GamesFillblankRouteImport } from './routes/games.fillblank'
import { Route as GamesCrosswordRouteImport } from './routes/games.crossword'
import { Route as GamesConjugationRouteImport } from './routes/games.conjugation'
import { Route as GamesBattleRouteImport } from './routes/games.battle'
import { Route as GrammarCasesCaseRouteImport } from './routes/grammar.cases.$case'

const VocabularyRoute = VocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const GrammarRoute = GrammarRouteImport.update({
  id: '/grammar',
  path: '/grammar',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyRoute = DailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesIdRoute = StoriesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StoriesRoute,
} as any)
const GrammarVerbsRoute = GrammarVerbsRouteImport.update({
  id: '/verbs',
  path: '/verbs',
  getParentRoute: () => GrammarRoute,
} as any)
const GrammarConnectionsRoute = GrammarConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => GrammarRoute,
} as any)
const GrammarConjugationRoute = GrammarConjugationRouteImport.update({
  id: '/conjugation',
  path: '/conjugation',
  getParentRoute: () => GrammarRoute,
} as any)
const GrammarAspectRoute = GrammarAspectRouteImport.update({
  id: '/aspect',
  path: '/aspect',
  getParentRoute: () => GrammarRoute,
} as any)
const GamesWordchainRoute = GamesWordchainRouteImport.update({
  id: '/wordchain',
  path: '/wordchain',
  getParentRoute: () => GamesRoute,
} as any)
const GamesSentenceRoute = GamesSentenceRouteImport.update({
  id: '/sentence',
  path: '/sentence',
  getParentRoute: () => GamesRoute,
} as any)
const GamesQuizRoute = GamesQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => GamesRoute,
} as any)
const GamesMemoryRoute = GamesMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => GamesRoute,
} as any)
const GamesMatchRoute = GamesMatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => GamesRoute,
} as any)
const GamesListeningRoute = GamesListeningRouteImport.update({
  id: '/listening',
  path: '/listening',
  getParentRoute: () => GamesRoute,
} as any)
const GamesFillblankRoute = GamesFillblankRouteImport.update({
  id: '/fillblank',
  path: '/fillblank',
  getParentRoute: () => GamesRoute,
} as any)
const GamesCrosswordRoute = GamesCrosswordRouteImport.update({
  id: '/crossword',
  path: '/crossword',
  getParentRoute: () => GamesRoute,
} as any)
const GamesConjugationRoute = GamesConjugationRouteImport.update({
  id: '/conjugation',
  path: '/conjugation',
  getParentRoute: () => GamesRoute,
} as any)
const GamesBattleRoute = GamesBattleRouteImport.update({
  id: '/battle',
  path: '/battle',
  getParentRoute: () => GamesRoute,
} as any)
const GrammarCasesCaseRoute = GrammarCasesCaseRouteImport.update({
  id: '/cases/$case',
  path: '/cases/$case',
  getParentRoute: () => GrammarRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/daily': typeof DailyRoute
  '/dashboard': typeof DashboardRoute
  '/games': typeof GamesRouteWithChildren
  '/grammar': typeof GrammarRouteWithChildren
  '/stories': typeof StoriesRouteWithChildren
  '/vocabulary': typeof VocabularyRoute
  '/games/battle': typeof GamesBattleRoute
  '/games/conjugation': typeof GamesConjugationRoute
  '/games/crossword': typeof GamesCrosswordRoute
  '/games/fillblank': typeof GamesFillblankRoute
  '/games/listening': typeof GamesListeningRoute
  '/games/match': typeof GamesMatchRoute
  '/games/memory': typeof GamesMemoryRoute
  '/games/quiz': typeof GamesQuizRoute
  '/games/sentence': typeof GamesSentenceRoute
  '/games/wordchain': typeof GamesWordchainRoute
  '/grammar/aspect': typeof GrammarAspectRoute
  '/grammar/conjugation': typeof GrammarConjugationRoute
  '/grammar/connections': typeof GrammarConnectionsRoute
  '/grammar/verbs': typeof GrammarVerbsRoute
  '/stories/$id': typeof StoriesIdRoute
  '/grammar/cases/$case': typeof GrammarCasesCaseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/daily': typeof DailyRoute
  '/dashboard': typeof DashboardRoute
  '/games': typeof GamesRouteWithChildren
  '/grammar': typeof GrammarRouteWithChildren
  '/stories': typeof StoriesRouteWithChildren
  '/vocabulary': typeof VocabularyRoute
  '/games/battle': typeof GamesBattleRoute
  '/games/conjugation': typeof GamesConjugationRoute
  '/games/crossword': typeof GamesCrosswordRoute
  '/games/fillblank': typeof GamesFillblankRoute
  '/games/listening': typeof GamesListeningRoute
  '/games/match': typeof GamesMatchRoute
  '/games/memory': typeof GamesMemoryRoute
  '/games/quiz': typeof GamesQuizRoute
  '/games/sentence': typeof GamesSentenceRoute
  '/games/wordchain': typeof GamesWordchainRoute
  '/grammar/aspect': typeof GrammarAspectRoute
  '/grammar/conjugation': typeof GrammarConjugationRoute
  '/grammar/connections': typeof GrammarConnectionsRoute
  '/grammar/verbs': typeof GrammarVerbsRoute
  '/stories/$id': typeof StoriesIdRoute
  '/grammar/cases/$case': typeof GrammarCasesCaseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/daily': typeof DailyRoute
  '/dashboard': typeof DashboardRoute
  '/games': typeof GamesRouteWithChildren
  '/grammar': typeof GrammarRouteWithChildren
  '/stories': typeof StoriesRouteWithChildren
  '/vocabulary': typeof VocabularyRoute
  '/games/battle': typeof GamesBattleRoute
  '/games/conjugation': typeof GamesConjugationRoute
  '/games/crossword': typeof GamesCrosswordRoute
  '/games/fillblank': typeof GamesFillblankRoute
  '/games/listening': typeof GamesListeningRoute
  '/games/match': typeof GamesMatchRoute
  '/games/memory': typeof GamesMemoryRoute
  '/games/quiz': typeof GamesQuizRoute
  '/games/sentence': typeof GamesSentenceRoute
  '/games/wordchain': typeof GamesWordchainRoute
  '/grammar/aspect': typeof GrammarAspectRoute
  '/grammar/conjugation': typeof GrammarConjugationRoute
  '/grammar/connections': typeof GrammarConnectionsRoute
  '/grammar/verbs': typeof GrammarVerbsRoute
  '/stories/$id': typeof StoriesIdRoute
  '/grammar/cases/$case': typeof GrammarCasesCaseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/daily'
    | '/dashboard'
    | '/games'
    | '/grammar'
    | '/stories'
    | '/vocabulary'
    | '/games/battle'
    | '/games/conjugation'
    | '/games/crossword'
    | '/games/fillblank'
    | '/games/listening'
    | '/games/match'
    | '/games/memory'
    | '/games/quiz'
    | '/games/sentence'
    | '/games/wordchain'
    | '/grammar/aspect'
    | '/grammar/conjugation'
    | '/grammar/connections'
    | '/grammar/verbs'
    | '/stories/$id'
    | '/grammar/cases/$case'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/daily'
    | '/dashboard'
    | '/games'
    | '/grammar'
    | '/stories'
    | '/vocabulary'
    | '/games/battle'
    | '/games/conjugation'
    | '/games/crossword'
    | '/games/fillblank'
    | '/games/listening'
    | '/games/match'
    | '/games/memory'
    | '/games/quiz'
    | '/games/sentence'
    | '/games/wordchain'
    | '/grammar/aspect'
    | '/grammar/conjugation'
    | '/grammar/connections'
    | '/grammar/verbs'
    | '/stories/$id'
    | '/grammar/cases/$case'
  id:
    | '__root__'
    | '/'
    | '/daily'
    | '/dashboard'
    | '/games'
    | '/grammar'
    | '/stories'
    | '/vocabulary'
    | '/games/battle'
    | '/games/conjugation'
    | '/games/crossword'
    | '/games/fillblank'
    | '/games/listening'
    | '/games/match'
    | '/games/memory'
    | '/games/quiz'
    | '/games/sentence'
    | '/games/wordchain'
    | '/grammar/aspect'
    | '/grammar/conjugation'
    | '/grammar/connections'
    | '/grammar/verbs'
    | '/stories/$id'
    | '/grammar/cases/$case'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DailyRoute: typeof DailyRoute
  DashboardRoute: typeof DashboardRoute
  GamesRoute: typeof GamesRouteWithChildren
  GrammarRoute: typeof GrammarRouteWithChildren
  StoriesRoute: typeof StoriesRouteWithChildren
  VocabularyRoute: typeof VocabularyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vocabulary': {
      id: '/vocabulary'
      path: '/vocabulary'
      fullPath: '/vocabulary'
      preLoaderRoute: typeof VocabularyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grammar': {
      id: '/grammar'
      path: '/grammar'
      fullPath: '/grammar'
      preLoaderRoute: typeof GrammarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily': {
      id: '/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof DailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/$id': {
      id: '/stories/$id'
      path: '/$id'
      fullPath: '/stories/$id'
      preLoaderRoute: typeof StoriesIdRouteImport
      parentRoute: typeof StoriesRoute
    }
    '/grammar/verbs': {
      id: '/grammar/verbs'
      path: '/verbs'
      fullPath: '/grammar/verbs'
      preLoaderRoute: typeof GrammarVerbsRouteImport
      parentRoute: typeof GrammarRoute
    }
    '/grammar/connections': {
      id: '/grammar/connections'
      path: '/connections'
      fullPath: '/grammar/connections'
      preLoaderRoute: typeof GrammarConnectionsRouteImport
      parentRoute: typeof GrammarRoute
    }
    '/grammar/conjugation': {
      id: '/grammar/conjugation'
      path: '/conjugation'
      fullPath: '/grammar/conjugation'
      preLoaderRoute: typeof GrammarConjugationRouteImport
      parentRoute: typeof GrammarRoute
    }
    '/grammar/aspect': {
      id: '/grammar/aspect'
      path: '/aspect'
      fullPath: '/grammar/aspect'
      preLoaderRoute: typeof GrammarAspectRouteImport
      parentRoute: typeof GrammarRoute
    }
    '/games/wordchain': {
      id: '/games/wordchain'
      path: '/wordchain'
      fullPath: '/games/wordchain'
      preLoaderRoute: typeof GamesWordchainRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/sentence': {
      id: '/games/sentence'
      path: '/sentence'
      fullPath: '/games/sentence'
      preLoaderRoute: typeof GamesSentenceRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/quiz': {
      id: '/games/quiz'
      path: '/quiz'
      fullPath: '/games/quiz'
      preLoaderRoute: typeof GamesQuizRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/memory': {
      id: '/games/memory'
      path: '/memory'
      fullPath: '/games/memory'
      preLoaderRoute: typeof GamesMemoryRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/match': {
      id: '/games/match'
      path: '/match'
      fullPath: '/games/match'
      preLoaderRoute: typeof GamesMatchRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/listening': {
      id: '/games/listening'
      path: '/listening'
      fullPath: '/games/listening'
      preLoaderRoute: typeof GamesListeningRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/fillblank': {
      id: '/games/fillblank'
      path: '/fillblank'
      fullPath: '/games/fillblank'
      preLoaderRoute: typeof GamesFillblankRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/crossword': {
      id: '/games/crossword'
      path: '/crossword'
      fullPath: '/games/crossword'
      preLoaderRoute: typeof GamesCrosswordRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/conjugation': {
      id: '/games/conjugation'
      path: '/conjugation'
      fullPath: '/games/conjugation'
      preLoaderRoute: typeof GamesConjugationRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/battle': {
      id: '/games/battle'
      path: '/battle'
      fullPath: '/games/battle'
      preLoaderRoute: typeof GamesBattleRouteImport
      parentRoute: typeof GamesRoute
    }
    '/grammar/cases/$case': {
      id: '/grammar/cases/$case'
      path: '/cases/$case'
      fullPath: '/grammar/cases/$case'
      preLoaderRoute: typeof GrammarCasesCaseRouteImport
      parentRoute: typeof GrammarRoute
    }
  }
}

interface GamesRouteChildren {
  GamesBattleRoute: typeof GamesBattleRoute
  GamesConjugationRoute: typeof GamesConjugationRoute
  GamesCrosswordRoute: typeof GamesCrosswordRoute
  GamesFillblankRoute: typeof GamesFillblankRoute
  GamesListeningRoute: typeof GamesListeningRoute
  GamesMatchRoute: typeof GamesMatchRoute
  GamesMemoryRoute: typeof GamesMemoryRoute
  GamesQuizRoute: typeof GamesQuizRoute
  GamesSentenceRoute: typeof GamesSentenceRoute
  GamesWordchainRoute: typeof GamesWordchainRoute
}

const GamesRouteChildren: GamesRouteChildren = {
  GamesBattleRoute: GamesBattleRoute,
  GamesConjugationRoute: GamesConjugationRoute,
  GamesCrosswordRoute: GamesCrosswordRoute,
  GamesFillblankRoute: GamesFillblankRoute,
  GamesListeningRoute: GamesListeningRoute,
  GamesMatchRoute: GamesMatchRoute,
  GamesMemoryRoute: GamesMemoryRoute,
  GamesQuizRoute: GamesQuizRoute,
  GamesSentenceRoute: GamesSentenceRoute,
  GamesWordchainRoute: GamesWordchainRoute,
}

const GamesRouteWithChildren = GamesRoute._addFileChildren(GamesRouteChildren)

interface GrammarRouteChildren {
  GrammarAspectRoute: typeof GrammarAspectRoute
  GrammarConjugationRoute: typeof GrammarConjugationRoute
  GrammarConnectionsRoute: typeof GrammarConnectionsRoute
  GrammarVerbsRoute: typeof GrammarVerbsRoute
  GrammarCasesCaseRoute: typeof GrammarCasesCaseRoute
}

const GrammarRouteChildren: GrammarRouteChildren = {
  GrammarAspectRoute: GrammarAspectRoute,
  GrammarConjugationRoute: GrammarConjugationRoute,
  GrammarConnectionsRoute: GrammarConnectionsRoute,
  GrammarVerbsRoute: GrammarVerbsRoute,
  GrammarCasesCaseRoute: GrammarCasesCaseRoute,
}

const GrammarRouteWithChildren =
  GrammarRoute._addFileChildren(GrammarRouteChildren)

interface StoriesRouteChildren {
  StoriesIdRoute: typeof StoriesIdRoute
}

const StoriesRouteChildren: StoriesRouteChildren = {
  StoriesIdRoute: StoriesIdRoute,
}

const StoriesRouteWithChildren =
  StoriesRoute._addFileChildren(StoriesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DailyRoute: DailyRoute,
  DashboardRoute: DashboardRoute,
  GamesRoute: GamesRouteWithChildren,
  GrammarRoute: GrammarRouteWithChildren,
  StoriesRoute: StoriesRouteWithChildren,
  VocabularyRoute: VocabularyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
